# dnsmasq configuration — Private DNS Server (Mac 1)
# Location on this machine: /opt/homebrew/etc/dnsmasq.conf
#
# See README_DNS.md in this folder for an explanation of each line.
 
listen-address=127.0.0.1,10.7.17.48
address=/powerpuffboys.test/10.7.12.202
 

